service: paper

# Create an optimized package for our functions
package:
  individually: true
  excludeDevDependencies: true

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  profile: ${env:PROFILE}
  region: ${env:REGION}
  timeout: 30

functions:
  login:
    handler: src/paper.hello
    events:
      - http:
          path: paper/hello
          method: post
          cors: true

resources:
  # API Gateway Errors
  - ${file(../../resources/api-gateway-errors.yml)}
